name: 360_AI_Sniper_Bot

on:
  schedule:
    # यह भारतीय समय (IST) के अनुसार 9:15 AM से 3:15 PM के बीच हर 15 मिनट में रन होगा।
    # (25 रन प्रति दिन x 1 मिनट = 25 मिनट/दिन। 1 महीने में मात्र 550 मिनट खर्च होंगे!)
    - cron: '45,0,15,30 3-9 * * 1-5'
  workflow_dispatch:

jobs:
  sniper_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install pandas yfinance requests pytz numpy
      - name: Execute 360 AI Engine
        env:
          DHAN_CLIENT_ID: ${{ secrets.DHAN_CLIENT_ID }}
          DHAN_ACCESS_TOKEN: ${{ secrets.DHAN_ACCESS_TOKEN }}
        run: python algo.py
